spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
  h2:
    console:
      enabled: false

app:
  storefront:
    url: ${STOREFRONT_URL:https://socialthngs.com}
